# Generated by Django 5.2.5 on 2025-11-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
